name: MineCore
version: '${project.version}'
main: com.xycm.frain.minecore.MineCore
api-version: '1.20'
authors: [ Frain ]

commands:
  minecore:
    description: MineCore 主命令

permissions:
  minecore.teleport.back:
    description: 允许使用 /minecore back 返回上一位置
    default: op
  minecore.teleport.spawn:
    description: 允许使用 /minecore spawn 传送到出生点
    default: op
  minecore.player.vanish:
    description: 允许使用 /minecore vanish 切换隐身模式
    default: op
  minecore.player.gamemode:
    description: 允许使用 /minecore gamemode 切换游戏模式
    default: op
  minecore.player.god:
    description: 允许使用 /minecore god 切换无敌模式
    default: op
  minecore.player.fly:
    description: 允许使用 /minecore fly 切换飞行模式
    default: op
  minecore.player.suicide:
    description: 允许使用 /minecore suicide 自杀
    default: op
  minecore.player.heal:
    description: 允许使用 /minecore heal 恢复生命值
    default: op
  minecore.player.help:
    description: 允许查看帮助信息
    default: op
  minecore.admin.reload:
    description: 允许重载 MineCore 配置与消息
    default: op
  minecore.teleport.home:
    description: 允许使用 /minecore home/sethome/delhome
    default: op
  minecore.teleport.warp:
    description: 允许使用 /minecore warp/setwarp/delwarp/warplist
    default: op
  minecore.teleport.tphere:
    description: 允许使用 /minecore tphere 传送玩家
    default: op
